FROM oven/bun:1.3.4-debian AS deps
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json bun.lock ./
COPY prisma ./prisma
RUN bun install --frozen-lockfile

FROM deps AS builder
WORKDIR /app

ARG AUTH_SECRET
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG CLOUDINARY_CLOUD_NAME
ARG DATABASE_URL
ARG DEPLOYMENT_VERSION
ARG GIT_COMMIT_SHA
ARG GIT_SHA
ARG NEYNAR_API_KEY
ARG NEXT_DEPLOYMENT_ID
ARG NEXT_PUBLIC_ACCOUNT_ASSOCIATION_HEADER
ARG NEXT_PUBLIC_ACCOUNT_ASSOCIATION_PAYLOAD
ARG NEXT_PUBLIC_ACCOUNT_ASSOCIATION_SIGNATURE
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_BASE_BUILDER_CODE
ARG NEXT_PUBLIC_BASE_MAINNET_RPC_URL
ARG NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL
ARG NEXT_PUBLIC_BLOCK_EXPLORER_URL
ARG NEXT_PUBLIC_CELO_MAINNET_RPC_URL
ARG NEXT_PUBLIC_CELO_SEPOLIA_RPC_URL
ARG NEXT_PUBLIC_CHAIN_NETWORK
ARG NEXT_PUBLIC_HOME_URL_PATH
ARG NEXT_PUBLIC_ONCHAINKIT_API_KEY
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_APP
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_MAINNET
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_SEPOLIA
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_FARCASTER
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_MINIPAY
ARG NEXT_PUBLIC_TREASURY_WALLET
ARG NEXT_PUBLIC_TREASURY_WALLET_MINIPAY
ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_BASE_APP
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_FARCASTER
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_MINIPAY
ARG NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
ARG SOURCE_COMMIT

ENV NODE_ENV=production

COPY . .
RUN bun run build
RUN cp -R public .next/standalone/public && \
  mkdir -p .next/standalone/.next && \
  cp -R .next/static .next/standalone/.next/static

FROM node:22-bookworm-slim AS runner
WORKDIR /app

ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV PORT=3000

RUN groupadd --system --gid 1001 nodejs
RUN useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
