FROM oven/bun:1.3.4-debian AS bun

FROM node:22-bookworm-slim AS deps
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun
COPY package.json bun.lock ./
COPY prisma ./prisma
RUN bun install --frozen-lockfile

FROM deps AS builder
WORKDIR /app

ARG DEPLOYMENT_VERSION
ARG GIT_COMMIT_SHA
ARG GIT_SHA
ARG NEXT_DEPLOYMENT_ID
ARG NEXT_PUBLIC_ACCOUNT_ASSOCIATION_HEADER
ARG NEXT_PUBLIC_ACCOUNT_ASSOCIATION_PAYLOAD
ARG NEXT_PUBLIC_ACCOUNT_ASSOCIATION_SIGNATURE
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_BASE_BUILDER_CODE
ARG NEXT_PUBLIC_BASE_MAINNET_RPC_URL
ARG NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL
ARG NEXT_PUBLIC_BLOCK_EXPLORER_URL
ARG NEXT_PUBLIC_CELO_MAINNET_RPC_URL
ARG NEXT_PUBLIC_CELO_SEPOLIA_RPC_URL
ARG NEXT_PUBLIC_CHAIN_NETWORK
ARG NEXT_PUBLIC_HOME_URL_PATH=/play
ARG NEXT_PUBLIC_ONCHAINKIT_API_KEY=build-time-placeholder
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_APP
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_MAINNET
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_SEPOLIA
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_FARCASTER
ARG NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_MINIPAY
ARG NEXT_PUBLIC_TREASURY_WALLET
ARG NEXT_PUBLIC_TREASURY_WALLET_MINIPAY
ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_BASE_APP
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_FARCASTER
ARG NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_MINIPAY
ARG SOURCE_COMMIT

ENV NODE_ENV=production
ENV NEXT_PUBLIC_ACCOUNT_ASSOCIATION_HEADER=$NEXT_PUBLIC_ACCOUNT_ASSOCIATION_HEADER
ENV NEXT_PUBLIC_ACCOUNT_ASSOCIATION_PAYLOAD=$NEXT_PUBLIC_ACCOUNT_ASSOCIATION_PAYLOAD
ENV NEXT_PUBLIC_ACCOUNT_ASSOCIATION_SIGNATURE=$NEXT_PUBLIC_ACCOUNT_ASSOCIATION_SIGNATURE
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_BASE_BUILDER_CODE=$NEXT_PUBLIC_BASE_BUILDER_CODE
ENV NEXT_PUBLIC_BASE_MAINNET_RPC_URL=$NEXT_PUBLIC_BASE_MAINNET_RPC_URL
ENV NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL=$NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL
ENV NEXT_PUBLIC_BLOCK_EXPLORER_URL=$NEXT_PUBLIC_BLOCK_EXPLORER_URL
ENV NEXT_PUBLIC_CELO_MAINNET_RPC_URL=$NEXT_PUBLIC_CELO_MAINNET_RPC_URL
ENV NEXT_PUBLIC_CELO_SEPOLIA_RPC_URL=$NEXT_PUBLIC_CELO_SEPOLIA_RPC_URL
ENV NEXT_PUBLIC_CHAIN_NETWORK=$NEXT_PUBLIC_CHAIN_NETWORK
ENV NEXT_PUBLIC_HOME_URL_PATH=$NEXT_PUBLIC_HOME_URL_PATH
ENV NEXT_PUBLIC_ONCHAINKIT_API_KEY=$NEXT_PUBLIC_ONCHAINKIT_API_KEY
ENV NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS=$NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS
ENV NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_APP=$NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_APP
ENV NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_MAINNET=$NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_MAINNET
ENV NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_SEPOLIA=$NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_SEPOLIA
ENV NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_FARCASTER=$NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_FARCASTER
ENV NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_MINIPAY=$NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_MINIPAY
ENV NEXT_PUBLIC_TREASURY_WALLET=$NEXT_PUBLIC_TREASURY_WALLET
ENV NEXT_PUBLIC_TREASURY_WALLET_MINIPAY=$NEXT_PUBLIC_TREASURY_WALLET_MINIPAY
ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS=$NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS
ENV NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_BASE_APP=$NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_BASE_APP
ENV NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_FARCASTER=$NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_FARCASTER
ENV NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_MINIPAY=$NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_MINIPAY

COPY . .
RUN export AUTH_SECRET=build-time-auth-secret \
  CLOUDINARY_API_KEY=build-time-cloudinary-key \
  CLOUDINARY_API_SECRET=build-time-cloudinary-secret \
  CLOUDINARY_CLOUD_NAME=build-time-cloudinary-cloud \
  DATABASE_URL=postgresql://postgres:postgres@localhost:5432/waffles_build \
  NEYNAR_API_KEY=build-time-neynar-key \
  NEXT_BUILD_CPUS=1 \
  NEXT_DEPLOYMENT_ID=docker-build \
  NEXT_STATIC_GENERATION_MAX_CONCURRENCY=1 \
  NEXT_STATIC_GENERATION_MIN_PAGES_PER_WORKER=100 \
  NODE_OPTIONS=--max-old-space-size=1536 && \
  : "${NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_MINIPAY:?NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_MINIPAY build arg is required}" && \
  : "${NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_MINIPAY:?NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_MINIPAY build arg is required}" && \
  : "${NEXT_PUBLIC_TREASURY_WALLET_MINIPAY:?NEXT_PUBLIC_TREASURY_WALLET_MINIPAY build arg is required}" && \
  : "${NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_FARCASTER:?NEXT_PUBLIC_WAFFLE_CONTRACT_ADDRESS_FARCASTER build arg is required}" && \
  : "${NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_FARCASTER:?NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_FARCASTER build arg is required}" && \
  : "${NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_MAINNET:?NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_MAINNET build arg is required}" && \
  : "${NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_SEPOLIA:?NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS_BASE_SEPOLIA build arg is required}" && \
  node ./node_modules/prisma/build/index.js generate && \
  node ./node_modules/next/dist/bin/next build --webpack
RUN cp -R public .next/standalone/public && \
  mkdir -p .next/standalone/.next && \
  cp -R .next/static .next/standalone/.next/static

FROM node:22-bookworm-slim AS runner
WORKDIR /app

ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV PORT=3000

RUN groupadd --system --gid 1001 nodejs
RUN useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
